version: '3.8'
services:
  postgres:
    image: postgres:15
    env_file: ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    env_file: ./.env
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - rabbitmq
    command: npm run start:dev

  # FE dev (auto reload, mount code, chạy "npm run dev")
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: ./.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - user-service
    command: npm run dev

  # FE production (build xong mới start, không mount code, chạy "npm start")
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./.env
    # KHÔNG mount volume để không bị mất .next
    ports:
      - '3000:3000'
    depends_on:
      - user-service
    command: npm start

volumes:
  pgdata:
  pgadmin_data:
